# Generated by Django 6.0.3 on 2026-03-06 16:07

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('pending', 'Pending Enrollment')], default='pending', max_length=10)),
                ('enrollment_token', models.CharField(default=secrets.token_hex, max_length=64, unique=True)),
                ('api_key_hash', models.CharField(blank=True, max_length=128)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255)),
                ('agent_version', models.CharField(blank=True, max_length=32)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('memory_used_mb', models.FloatField()),
                ('memory_total_mb', models.FloatField()),
                ('disk_percent', models.FloatField()),
                ('disk_used_gb', models.FloatField()),
                ('disk_total_gb', models.FloatField()),
                ('load_1m', models.FloatField(default=0)),
                ('load_5m', models.FloatField(default=0)),
                ('load_15m', models.FloatField(default=0)),
                ('uptime_seconds', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='servers.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='servers_met_server__0ceb01_idx')],
            },
        ),
    ]
