# Generated by Django 6.0.3 on 2026-03-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_ssh_host_server_ssh_password_server_ssh_port_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='ssh_host',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_user',
        ),
    ]
