# Generated by Django 6.0.3 on 2026-03-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_server_ssh_host_remove_server_ssh_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_user',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='ServerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_notes', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
